---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.1
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.1
    hooks:
      - id: yamllint
        alias: yamllint-non-ansible
        name: yamllint (non-Ansible)
        files: '^[^(ci/)].*\.ya?ml$'
      - id: yamllint
        alias: yamllint-ansible
        name: yamllint (Ansible)
        files: '^ci/.*\.ya?ml$'
        args:
          - -c
          - .yamllint-ansible.yml
