- job:
    name: pre-commit
    run: ci/pre-commit.yaml
    nodeset: fedora-31-vm
- job:
    name: pytest
    run: ci/pytest.yaml
    nodeset: fedora-31-vm
- job:
    name: rpmbuild
    run: ci/rpmbuild.yaml
    nodeset: fedora-31-vm
- project:
    check:
      jobs:
        - pre-commit
        - pytest
        - rpmbuild
