---
- project:
    check:
      jobs:
        - fi-pre-commit
        - fi-pytest-rawhide:
            vars:
              dependencies:
                - glibc-langpack-de
                - glibc-langpack-en
                - python3-babel
                - python3-koji
                - python3-pygit2
                - python3-pytest
                - python3-pytest-cov
                - python3-pyyaml
                - python3-rpm
        - fi-pytest-f34:
            vars:
              dependencies:
                - glibc-langpack-de
                - glibc-langpack-en
                - python3-babel
                - python3-koji
                - python3-pygit2
                - python3-pytest
                - python3-pytest-cov
                - python3-pyyaml
                - python3-rpm
        - fi-pytest-f35:
            vars:
              dependencies:
                - glibc-langpack-de
                - glibc-langpack-en
                - python3-babel
                - python3-koji
                - python3-pygit2
                - python3-pytest
                - python3-pytest-cov
                - python3-pyyaml
                - python3-rpm
        - rpm-mock-build:
            vars:
              mock_config: fedora-35-x86_64
              build_from_source: true
              version_from_specfile: true
              src_name: rpmautospec
            nodeset:
              nodes:
                name: test-node
                label: zuul-worker-f35
