---
- project:
    check:
      jobs:
        - fi-pre-commit

        - fi-tox-python312:
            vars:
              dependencies:
                - gcc
                - glibc-langpack-de
                - glibc-langpack-en
                - libffi-devel
                - libgit2-devel
                - poetry
                - python3.12-devel

        - fi-tox-python311:
            vars:
              dependencies:
                - gcc
                - glibc-langpack-de
                - glibc-langpack-en
                - libffi-devel
                - libgit2-devel
                - poetry
                - python3.11-devel

        - fi-tox-python310:
            vars:
              dependencies:
                - gcc
                - glibc-langpack-de
                - glibc-langpack-en
                - libffi-devel
                - libgit2-devel
                - poetry
                - python3.10-devel

        - fi-tox-python39:
            vars:
              dependencies:
                - gcc
                - glibc-langpack-de
                - glibc-langpack-en
                - libffi-devel
                - libgit2-devel
                - poetry
                - python3.9-devel

        - rpm-mock-build:
            vars:
              mock_config: fedora-38-x86_64
              build_from_source: true
              version_from_specfile: true
              src_name: rpmautospec
            nodeset:
              nodes:
                name: test-node
                label: cloud-fedora-38
